version: '3'

services:
  server:
    image: linuxserver/letsencrypt
    container_name: server
    volumes:
     - ./volumes/server/config:/config
     - ./nginx/radicale.conf:/config/nginx/proxy-confs/radicale.subdomain.conf
     - ./nginx/wallabag.conf:/config/nginx/proxy-confs/wallabag.subdomain.conf
     - ./nginx/bitwarden.conf:/config/nginx/proxy-confs/bitwarden.subdomain.conf
     - ./nginx/nextcloud.conf:/config/nginx/proxy-confs/nextcloud.subdomain.conf
     - ./nginx/standardfiles.conf:/config/nginx/proxy-confs/standardfiles.subdomain.conf
    ports:
     - "80:80"
     - "443:443"
    cap_add:
     - NET_ADMIN
    environment:
      - URL=${DOMAIN_NAME}
      - SUBDOMAINS=wb,bw,sf,nc
      - VALIDATION=http
      - TZ=Europe/Madrid
      - PGID=1001
      - PUID=1001
