version: '3'

services:
  #wireguard:
  #  image: activeeos/wireguard-docker
  #  cap_add:
  #   - NET_ADMIN
  #   - SYS_MODULE
  #  volumes:
  #   - /wireguard:/etc/wireguard
  #   - /lib/modules:/lib/modules
  #  ports:
  #   - "51820:51820"
    
  server:
    image: linuxserver/letsencrypt
    container_name: server
    volumes:
     - ./volumes/server/config:/config
     - ./nginx/radicale.conf:/config/nginx/proxy-confs/radicale.subdomain.conf
     - ./nginx/wallabag.conf:/config/nginx/proxy-confs/wallabag.subdomain.conf
     - ./nginx/kanboard.conf:/config/nginx/proxy-confs/kanboard.subdomain.conf
     - ./nginx/bitwarden.conf:/config/nginx/proxy-confs/bitwarden.subdomain.conf
     - ./nginx/standardnotes.conf:/config/nginx/proxy-confs/standardnotes.subdomain.conf
    ports:
     - "80:80"
     - "443:443"
    cap_add:
     - NET_ADMIN
    environment:
      - URL=${DOMAIN_NAME}
      - SUBDOMAINS=rc,wb,bw,kb,sn,sf
      - VALIDATION=http
      - TZ=Europe/Madrid
      - PGID=1001
      - PUID=1001
