version: '3'

services:
  radicale:
    image: tomsquest/docker-radicale
    ports:
      - "81:5232"
    read_only: true
    volumes:
     - ./volumes/radicale/data/:/data
     - ./volumes/radicale/config/:/config

  bitwarden:
    container_name: bitwarden
    image: mprasil/bitwarden
    ports:
     - "82:80"
    volumes:
     - ./volumes/bitwarden/data/:/data/
    environment:
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "https://bw.${DOMAIN_NAME}"
     

  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    environment:
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
      - SYMFONY__ENV__DOMAIN_NAME="https://wb.${DOMAIN_NAME}"
    ports:
     - "83:80"
    volumes:
     - ./volumes/wallabag/data/:/var/www/wallabag/data
     - ./volumes/wallabag/images:/var/www/wallabag/web/assets/images

  standardfile:
    build:
      context: ./standardfile
      dockerfile: Dockerfile
    depends_on:
      - standardfile_db
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=use "bundle exec rake secret"
      - RAILS_SERVE_STATIC_FILES=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=items
      - DB_USERNAME=root
      - DB_PASSWORD=${STANDARDFILE_DB_PASSWORD}
      - SALT_PSEUDO_NONCE=use "bundle exec rake secret"
    links:
      - standardfile_db:db
    ports:
      - "84:3000"
      
  standardfile_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${STANDARDFILE_DB_PASSWORD}
    volumes:
      - ./volumes/standardfile/db:/var/lib/mysql
      
  syncthing:
    image: linuxserver/syncthing
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    environment:
      - PGID=1001
      - PUID=1001
    volumes:
     - ./volumes/syncthing/config/:/config/
     - ./volumes/syncthing/mnt/:/mnt/
